server:
  port: 8100

spring:
  profiles:
    active: native
  application:
    name: config-server
  rabbitmq:
    host: localhost
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS