server:
  port: 8081
spring:
  application:
    name: review-service
  datasource:
    #url: jdbc:mysql://app_db:3306/demodb
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka:8761/eureka/
      defaultZone: http://localhost:8761/eureka/